### ISSUE TITLE
Download button doesn't work

### ISSUE THREAD

**Issue by mamod** [crate/crate-web#184]
download button at page
https://github.com/crate/crate-web/blob/master/crate/pages/install/index.html#L78
doesn't work

from main.js there is an error at line
https://github.com/crate/crate-web/blob/master/crate/static/js/main.js#L42

``TypeError: this.email is undefined``

which prevent download link to resume, I would contribute a fix to this but I'm not sure what's the email for and there is no email field in the download form

**Comment by chaudum** [comment]
hi @mamod 
thanks for reporting. we had a optional email form on the download page until recently and it seems that removing that broke something.
we'll fix it asap, until then you can download the latest version from https://crate.io/docs/

best, christian

**Comment by mamod** [comment]
I couldn't wait so I already downloaded latest release from
https://cdn.crate.io/downloads/releases/
Thanks :)

**Comment by ChrisChinchilla** [comment]
Hi @mamod this should be now fixed, but I would appreciate you double checking for me.

**Comment by mamod** [comment]
@ChrisChinchilla umm I can see the changes but you may forget to update content on the server :) 

using chrome and opera, form doesn't break on ``email checking`` error instead it will redirect to [https://crate.io/install/?](https://crate.io/install/?) where it says  ``download stable version  0.49.4`` and only then the download will start for the older version, this doesn't happen with firefox ... not important just an extra debugging habit :)

**Comment by ChrisChinchilla** [comment]
Hmm.

I checked myself and it worked. Have you tried a hard refresh in the
browser?

Chris

**Comment by mamod** [comment]
of course, I also tried with 2 different browsers with no previous cache for crate.io, and I always land on page install where it says stable version ``0.49.6`` but when using wget it fetches install page which point to stable version ``0.96.4`` this is weird, I must be doing something wrong :(

I'll investigate and ping you back.

**Comment by ChrisChinchilla** [comment]
Most strange @mamod I tried again and on my phone and it works. Anything unusual in your setup I should know about?

**Comment by mamod** [comment]
Man, it's working now :) I don't know what was wrong but I'm sure it wasn't a local caching issue, sorry for the confusion and thank you very much :+1:
