### ISSUE TITLE
Broken /clients and /faq links

### ISSUE THREAD

**Issue by ckrybus** [crate/crate-web#278]
Hi,

the https://crate.io/docs/faq/ and https://crate.io/docs/clients/ pages are missing or the links are broken. Both are linked from the "Overview Installation Server Clients FAQ Source" menu.

**Comment by ChrisChinchilla** [comment]
Thanks @ckrybus I'm not sure where you are seeing this menu? That sounds like the menu from our old website, not the one we just relaunched.

**Comment by ckrybus** [comment]
@ChrisChinchilla yes, but the old website is available as reference/docs and the links there are not working anymore

[Homepage](https://crate.io/) ->  [Documentation - at the very top](https://crate.io/docs) -> [Reference docs - bottom left](https://crate.io/docs/reference/) -> [Clients - menu on blue background](https://crate.io/docs/clients/)

[Homepage](https://crate.io/) ->  [Documentation - at the very top](https://crate.io/docs) -> [Reference docs - bottom left](https://crate.io/docs/reference/) -> [FAQ - menu on blue background](https://crate.io/docs/faq/)

**Comment by joemoe** [comment]
thanks we removed and corrected the links.
