### ISSUE TITLE
Broken Link File Not found

### ISSUE THREAD

**Issue by duichwer** [crate/crate-web#484]
Hi on your website on link leads to a 404
On this site
https://crate.io/overview/high-level-architecture/

there is a link to a technical overview
https://cdn.crate.io/media/1602/crate-technical-overview.pdf
that is broken.

**Comment by celaus** [comment]
Hi, thanks for the heads up, we recently changed our website backend, so there are some loose ends ;) it will be fixed soon!

Cheers, Claus

**Comment by joemoe** [comment]
closing this for now as our website has been revamped.
