### ISSUE TITLE
Docs: Mention ALTER TABLE limits on DDL page

### ISSUE THREAD

**Issue by cweiske** [crate/crate-web#490]
The ALTER TABLE documentation says nothing about the issue that columns cannot be changed: https://crate.io/docs/reference/sql/ddl.html#alter-table

Please mention that there directly, or at least link directly to https://crate.io/docs/reference/sql/crate-standard-sql.html#alter-table

**Comment by chaudum** [comment]
hi @cweiske thanks for pointing it out. we will have a look how we can improve the documentation about these limitations.

**Comment by mfussenegger** [comment]
I think this has been resolved with https://github.com/crate/crate/commit/e916527cfbd9bf571bfde2b1039371207b07620f
